"""Graph Building and Analysis Service.

This service encapsulates business logic for:
- Building knowledge graphs from documents
- Analyzing relationships and entities
- Generating insights from graph structure
"""

import importlib.util
import os
from typing import Dict, Any, List, Optional

from .container import Service


class GraphService(Service):
    """Service for graph building and analysis."""
    
    def initialize(self) -> None:
        """Initialize graph service."""
        from ..config import Config
        self.config = Config
    
    def shutdown(self) -> None:
        """Cleanup graph service resources."""
        pass
    
    def build_graph(self, project_id: str, document_path: str) -> Dict[str, Any]:
        """Build a knowledge graph from a document.
        
        Args:
            project_id: Project ID
            document_path: Path to document
            
        Returns:
            Graph data with nodes and relationships
        """
        if not document_path or not os.path.exists(document_path):
            raise FileNotFoundError(f"Document not found: {document_path}")

        from ..services.graph_builder import GraphBuilderService

        with open(document_path, 'r', encoding='utf-8', errors='ignore') as fh:
            text = fh.read()

        builder = GraphBuilderService()
        task_id = builder.build_graph_async(
            text=text,
            ontology={"entity_types": [], "edge_types": [], "analysis_summary": "Generated by GraphService"},
            graph_name=f"project_{project_id}"
        )

        return {
            "project_id": project_id,
            "status": "queued",
            "task_id": task_id,
            "document_path": document_path,
        }
    
    def analyze_graph(self, project_id: str) -> Dict[str, Any]:
        """Analyze a graph for insights."""
        return {
            "project_id": project_id,
            "status": "available",
            "summary": "Graph analysis is handled by the existing graph_builder and ontology pipeline.",
        }


class SimulationService(Service):
    """Service for running simulations (OASIS)."""
    
    def initialize(self) -> None:
        """Initialize simulation service."""
        from ..config import Config
        self.config = Config
    
    def shutdown(self) -> None:
        """Cleanup simulation service resources."""
        pass
    
    def start_simulation(self, project_id: str, simulation_type: str,
                        config: Dict[str, Any]) -> str:
        """Start a new simulation."""
        from ..services.simulation_manager import SimulationManager

        graph_id = config.get('graph_id') or config.get('graphId')
        if not graph_id:
            raise ValueError("graph_id is required to create a simulation")

        state = SimulationManager().create_simulation(
            project_id=project_id,
            graph_id=graph_id,
            enable_twitter=simulation_type.lower() in {'twitter', 'all'} or config.get('enable_twitter', True),
            enable_reddit=simulation_type.lower() in {'reddit', 'all'} or config.get('enable_reddit', True),
        )
        return state.simulation_id
    
    def get_simulation_status(self, simulation_id: str) -> Dict[str, Any]:
        """Get status of a running simulation."""
        from ..services.simulation_manager import SimulationManager

        state = SimulationManager().get_simulation(simulation_id)
        if state is None:
            raise ValueError(f"Simulation not found: {simulation_id}")
        return state.to_dict()
    
    def list_simulations(self, project_id: str) -> List[Dict[str, Any]]:
        """List all simulations for a project."""
        from ..services.simulation_manager import SimulationManager

        return [state.to_dict() for state in SimulationManager().list_simulations(project_id)]


class ReportService(Service):
    """Service for generating reports."""
    
    def initialize(self) -> None:
        """Initialize report service."""
        from ..config import Config
        self.config = Config
    
    def shutdown(self) -> None:
        """Cleanup report service resources."""
        pass
    
    def generate_report(self, project_id: str, report_type: str) -> Dict[str, Any]:
        """Generate a report for a project.
        
        Returns a report summary if the report already exists, or an execution
        hint for the legacy report generator pipeline.
        """
        from ..services.simulation_manager import SimulationManager
        from ..services.report_agent import ReportManager

        simulations = SimulationManager().list_simulations(project_id)
        if not simulations:
            raise ValueError(f"No simulations found for project: {project_id}")

        latest = simulations[-1]
        report = ReportManager.get_report_by_simulation(latest.simulation_id)
        if report is not None:
            return report.to_dict()

        return {
            "project_id": project_id,
            "simulation_id": latest.simulation_id,
            "status": "not_generated",
            "report_type": report_type,
            "message": "Use the existing report API pipeline to generate and save the report.",
        }


class YouTubeService(Service):
    """Service for YouTube integration and Mirror Fish."""
    
    def initialize(self) -> None:
        """Initialize YouTube service."""
        from ..config import Config
        self.config = Config
    
    def shutdown(self) -> None:
        """Cleanup YouTube service resources."""
        pass
    
    def search_courses(self, query: str, max_results: int = 10) -> List[Dict[str, Any]]:
        """Search for course videos on YouTube."""
        if not query or not query.strip():
            raise ValueError("Query cannot be empty")

        helper_path = os.path.abspath(
            os.path.join(os.path.dirname(__file__), '..', 'boi-rsu', 'youtube.py')
        )
        spec = importlib.util.spec_from_file_location('mirofish_boi_rsu_youtube', helper_path)
        if spec is None or spec.loader is None:
            raise RuntimeError(f"Unable to load YouTube helper from {helper_path}")

        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module.get_videos_for_section(query, '', max_results=max_results)
    
    def get_video_recommendations(self, topic: str, level: str = 'beginner') -> List[Dict[str, Any]]:
        """Get recommended videos for a topic."""
        return self.search_courses(f"{topic} {level} tutorial", max_results=3)
